# Generated by Django 4.1.7 on 2023-12-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_students', to='stuff.profile', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_teachers', to='stuff.profile', verbose_name='Менеджер'),
        ),
    ]
