# Generated by Django 4.1.7 on 2023-12-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_student_manager_teacher_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='stuff.profile', verbose_name='Профиль'),
        ),
    ]
