# Generated by Django 4.1.7 on 2023-12-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_teacher_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rmv',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rmv',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='stuff.profile', verbose_name='Профиль'),
        ),
    ]
