# Generated by Django 4.1.7 on 2023-12-17 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_student_rmv_teacher_rmv_alter_contact_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Продолжительность')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменен')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Проведен')),
                ('is_moved', models.BooleanField(default=False, verbose_name='Перенесен')),
                ('moved_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stuff.lesson', verbose_name='Перенесено на дату')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='stuff.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='stuff.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Продолжительность')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='stuff.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='stuff.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
