# Generated by Django 4.1.7 on 2023-12-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_lesson_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='stuff.class', verbose_name='Окно'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'student', 'day', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('teacher', 'student', 'date', 'start_time')},
        ),
    ]
