# Generated by Django 4.1.7 on 2023-12-08 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuff', '0003_alter_teacher_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('participants', models.ManyToManyField(related_name='chats', to='stuff.profile')),
            ],
        ),
    ]
