# Generated by Django 4.1.7 on 2023-12-02 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_teacher_profile'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='first_person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chats_first_person', to='stuff.profile', verbose_name='Профиль 1'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='second_person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chats_second_person', to='stuff.profile', verbose_name='Профиль 2'),
        ),
    ]
