# Generated by Django 4.1.7 on 2023-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название чата'),
        ),
        migrations.AddField(
            model_name='chat',
            name='rmv',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
