# Generated by Django 4.1.7 on 2023-12-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_teacher_profile'),
        ('messenger', '0002_alter_chat_first_person_alter_chat_second_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chat',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_chats', to='stuff.profile', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='chat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_chat', to='stuff.profile', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='chat',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_chats', to='stuff.profile', verbose_name='Профиль 2'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('manager', 'teacher', 'student')},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='second_person',
        ),
    ]
