# Generated by Django 4.1.7 on 2023-12-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_personal',
            field=models.BooleanField(default=True, verbose_name='Персональный'),
        ),
    ]
